### PR TITLE
Rename adminitration.py to administration.py

### PR DESCRIPTION
**Pull request by giraffekey**
Whoopsies

### CODE REVIEW

**Comment by giraffekey** [comment]
Whoops, didn't mean to close this.
Didn't realize the new commits were automatically added to the PR.
Here is the list of changes:
- Commands: kick, ban, unban, tempban, mute, unmute, tempmute, clear
- Created a .gitignore
- Added new dependencies: discord-timers and python-dateutil
- Created a time.py file to help with timers and time parsing (So that you can say things like "1m20s" in commands)

**Review by jcsumlin — APPROVED** [review]
I think that we should use embeds as responses for a better aesthetic. Can you make a new PR once this is merged to update that? Also please use the loguru package for logging instead of printing to the console (https://github.com/Delgan/loguru).
Finally, please include comments on all commands to instruct a user on how to use them. This may be relocated to dedicated documentation at another time but it will be good to have it in the code for our own reference as well.

**Comment by giraffekey** [comment]
:+1:

**Comment by giraffekey** [comment]
This pull request *also* will contain two commands for role menus and some SQL code

**Pull request merged**
